#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'


gsutil mb --pap enforced gs://tfstate.decibelduck.com
gsutil versioning set on gs://tfstate.decibelduck.com


echo '# terraform init -backend-config="bucket=tfstate.decibelduck.com"'
